/* GENERATE ALERT. IT IS GOING TO DISPLAY MESSAGES IN OUR APP */
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const RESET_ALERT = 'RESET_ALERT';

/* ACTIVATE A USER AFTER A FIRST LOGGED IN */
export const ACTIVATE_USER = 'ACTIVATE_USER';

/* PROFESSONAL */
export const UPDATE_SCHEDULE_PRO = 'UPDATE_SCHEDULE_PRO';