export const PROCESSING = 'PROCESSING';
/* GENERATE ALERT. IT IS GOING TO DISPLAY MESSAGES IN OUR APP */
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const RESET_ALERT = 'RESET_ALERT';

/* ACTIVATE A USER AFTER A FIRST LOGGED IN */
export const ACTIVATE_USER = 'ACTIVATE_USER';

/* PROFESSONAL */
export const UPDATE_SCHEDULE_PRO = 'UPDATE_SCHEDULE_PRO';
export const UPDATE_MY_CRITERIA = 'UPDATE_MY_CRITERIA';
export const GET_TIME_SCHEDULED_ACTIVITIES = 'GET_TIME_SCHEDULED_ACTIVITIES';

/* RESERVATION */
export const GET_RESERVATIONS_LIST = 'GET_RESERVATIONS_LIST';
export const GET_A_REQUEST = 'GET_A_REQUEST';

/* CLIENT */
export const ESTIMATION_LOCATION_UPDATE = 'ESTIMATION_LOCATION_UPDATE';
export const ESTIMATION_HOUSING_UPDATE = 'ESTIMATION_HOUSING_UPDATE';
export const ESTIMATION_HOUSING_VALIDATION_SUCCESS = 'ESTIMATION_HOUSING_SUCCESS';
export const ESTIMATION_HOUSING_VALIDATION_ERROR = 'ESTIMATION_HOUSING_ERROR';
export const ESTIMATION_BENEFIT_UPDATE = 'ESTIMATION_BENEFIT_UPDATE';
export const ESTIMATION_BENEFIT_VALIDATION_SUCCESS = 'ESTIMATION_BENEFIT_SUCCESS';
export const ESTIMATION_BENEFIT_VALIDATION_ERROR = 'ESTIMATION_BENEFIT_ERROR';
export const ESTIMATION_PERSONAL_DATA_UPDATE = 'ESTIMATION_PERSONAL_DATA_UPDATE';
export const FETCH_ESTIMATION = 'FETCH_ESTIMATION';